import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/layout/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { dark } from "@clerk/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorPrimary: "var(--primary)",
          colorForeground: "var(--foreground)",
        },
      }}
    >
      <html lang="en" suppressHydrationWarning className="dark">
        <head />
        <body>
          <Toaster richColors />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
